apiVersion: cve-release.skynetx.me/v1
kind: GitHubReleasesMonitor
metadata:
  labels:
    app.kubernetes.io/name: cve-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubreleasesmonitor-sample
spec:
  url: "https://github.com/CVEProject/cvelistV5/releases"
  monitorfrom: "now"
  dockersecret: "docker-hub-pat-reference-name"
  kafkauser: "user1"
  kafkapassword: "kafka-password"
  kafkabroker0: "kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092"
  kafkabroker1: "kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092"
  kafkabroker2: "kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092"
  image: "vkneu7/pinecone-loader:v1.0.0"
  pineconekey: "Your-Pinecone-Project-Key"
  pineconecloud: "aws"
  pineconeenv: "cve"
  pineconeregion: "us-east-1"