# Default values for cve-processor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "vkneu7/cve-operator"
  pullPolicy: "Always"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "arm"
container:
  name: cve-operator

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 128Mi

env:
  # - name: DB_HOST
  #   value: postgresql # host.docker.internal for local postgres
  # - name: DB_USER
  #   value: web_app
  # - name: DB_PASSWORD
  #   valueFrom: 
  #     secretKeyRef:
  #       name: db-password-secret
  #       key: DB_PASSWORD
  # - name: DB
  #   value: cve
  # - name: DB_PORT
  #   value: "5432"
  # - name: DB_SCHEMA
  #   value: cve  
  - name: dockerSecret
    value: docker-hub-pat
  - name: KAFKA_USER
    value: user1
  - name: KAFKA_PASSWORD
    valueFrom: 
      secretKeyRef:
        name: kafka-secret
        key: KAFKA_PASSWORD
  - name: KAFKA_BROKER_0
    value: kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092
  - name: KAFKA_BROKER_1
    value: kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092
  - name: KAFKA_BROKER_2
    value: kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092      

affinitylabel: cve-operator

secrets: 
  dbPassword: "placeholder_for_db_password"
  dockerConfigJson: "placeholder_for_docker_config_json"
  kafkaPassword: "placeholder_for_kafka_password" 

# networkPolicy:
#   enabled: true
#   namespace: cve-operator
#   denyAll:
#     name: cve-deny-all
#     appLabel: cve-db
#   postgresPolicy:
#     name: postgres-network-policy
#     appLabel: cve-db
#     port: 5432
#     fromAppLabel: cve-consumer

serviceAccountName: githubreleasesmonitor-sa

