# Default values for cve-processor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "vkneu7/cve-operator"
  pullPolicy: "Always"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.2.0"
container:
  name: cve-operator

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 128Mi

env: 
  - name: dockerSecret
    value: docker-hub-pat
  - name: KAFKA_USER
    value: user1
  - name: KAFKA_PASSWORD
    valueFrom: 
      secretKeyRef:
        name: kafka-secret
        key: KAFKA_PASSWORD
  - name: KAFKA_BROKER_0
    value: kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092
  - name: KAFKA_BROKER_1
    value: kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092
  - name: KAFKA_BROKER_2
    value: kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092      

affinitylabel: cve-operator

secrets: 
  dbPassword: "placeholder_for_db_password"
  dockerConfigJson: "placeholder_for_docker_config_json"
  kafkaPassword: "placeholder_for_kafka_password" 

serviceAccountName: githubreleasesmonitor-sa

